name: Registry
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch: {}

env:
  BUCKET: oam-website
  ENDPOINT: oss-cn-beijing.aliyuncs.com
  ACCESS_KEY: ${{ secrets.OSS_ACCESS_KEY }}
  ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
  ARTIFACT_HUB_REPOSITORY_ID: ${{ secrets.ARTIFACT_HUB_REPOSITORY_ID }}

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}
      - name: Get git revision
        id: vars
        shell: bash
        run: |
          echo "::set-output name=git_revision::$(git rev-parse --short HEAD)"
      - name: Login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Login docker.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        name: Build & Pushing
        with:
          context: .
          file: Dockerfile
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            GITVERSION=git-${{ steps.vars.outputs.git_revision }}
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |-
            ghcr.io/${{ github.repository }}/vela-core:${{ steps.get_version.outputs.VERSION }}
            docker.io/oamdev/vela-core:${{ steps.get_version.outputs.VERSION }}

  publish-charts:
    env:
      HELM_CHARTS_DIR: charts
      HELM_CHART: charts/vela-core
      LEGACY_HELM_CHART: legacy/charts/vela-core-legacy
      LOCAL_OSS_DIRECTORY: .oss/
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Get git revision
        id: vars
        shell: bash
        run: |
          echo "::set-output name=git_revision::$(git rev-parse --short HEAD)"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Prepare legacy chart
        run: |
          rsync -r $LEGACY_HELM_CHART $HELM_CHARTS_DIR
          rsync -r $HELM_CHART/* $LEGACY_HELM_CHART --exclude=Chart.yaml --exclude=crds
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: oam-dev/kubevela
          releases-only: true
        id: latest_tag
      - name: Tag helm chart image
        run:  |
          latest_repo_tag=${{ steps.latest_tag.outputs.tag }}
          sub="."
          major="$(cut -d"$sub" -f1 <<<"$latest_repo_tag")"
          minor="$(cut -d"$sub" -f2 <<<"$latest_repo_tag")"
          patch="0"
          next_repo_tag="$major.$(($minor + 1)).$patch"
          image_tag=${GITHUB_REF#refs/tags/}
          chart_version=${latest_repo_tag#"v"}
          if [[ ${GITHUB_REF} == "refs/heads/master" ]]; then
            image_tag=latest
            chart_version=${next_repo_tag}-rc-master
          fi
          image_tag=latest
          chart_version=${next_repo_tag}-rc-master
          sed -i "s/latest/${image_tag}/g" $HELM_CHART/values.yaml
          sed -i "s/latest/image_tag/g" $LEGACY_HELM_CHART/values.yaml
          sed -i "s/0.1.0/$chart_version/g" $HELM_CHART/Chart.yaml
          sed -i "s/0.1.0/$chart_version/g" $LEGACY_HELM_CHART/Chart.yaml
          cat $HELM_CHART/Chart.yaml
          echo "---------------"
          cat $LEGACY_HELM_CHART/Chart.yaml
      - name: Install ossutil
        run: wget http://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 && chmod +x ossutil64 && mv ossutil64 ossutil
      - name: Configure Alibaba Cloud OSSUTIL
        run: ./ossutil --config-file .ossutilconfig config -i ${ACCESS_KEY} -k ${ACCESS_KEY_SECRET} -e ${ENDPOINT} -c .ossutilconfig
      - name: sync cloud to local
        run: ./ossutil --config-file .ossutilconfig sync oss://$BUCKET/core $LOCAL_OSS_DIRECTORY
      - name: add artifacthub stuff to the repo
        run: |
          rsync docs/en/install.md $HELM_CHART/README.md
          rsync docs/en/install.md $LEGACY_HELM_CHART/README.md
          sed -i "s/ARTIFACT_HUB_REPOSITORY_ID/$ARTIFACT_HUB_REPOSITORY_ID/g" hack/artifacthub/artifacthub-repo.yml
          rsync hack/artifacthub/artifacthub-repo.yml $LOCAL_OSS_DIRECTORY
      - name: Package helm charts
        run: |
          helm package $HELM_CHART --destination $LOCAL_OSS_DIRECTORY
          helm package $LEGACY_HELM_CHART --destination $LOCAL_OSS_DIRECTORY
          helm repo index --url https://$BUCKET.$ENDPOINT/core $LOCAL_OSS_DIRECTORY
      - name: sync local to cloud
        run: ./ossutil --config-file .ossutilconfig sync $LOCAL_OSS_DIRECTORY oss://$BUCKET/core -f
